version: '3'
services:
  web:
    build: .
    command: python server.py
    ports:
      - "5000:5000"
    volumes:
      - .:/yolk-take-home
    links:
      - db
  db:
    image: mongo:3
    ports:
      - "27017:27017"